"""initial

Revision ID: 067a43a9897b
Revises: 
Create Date: 2026-05-26 21:37:44.389096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067a43a9897b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animales',
    sa.Column('id_animal', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('tamanio', sa.String(), nullable=False),
    sa.Column('raza', sa.String(), nullable=True),
    sa.Column('colores', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('info_adicional', sa.Text(), nullable=True),
    sa.Column('comportamiento', sa.Text(), nullable=True),
    sa.Column('esterilizado', sa.Boolean(), nullable=False),
    sa.Column('url_imagen', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_animal')
    )
    op.create_table('compatibilidades',
    sa.Column('id_compatibilidad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_compatibilidad'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estados',
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_estado'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('personas',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_persona'),
    sa.UniqueConstraint('email')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tareas',
    sa.Column('id_tarea', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('es_todo_el_dia', sa.Boolean(), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_tarea')
    )
    op.create_table('animales_compatibilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('compatibilidad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id_animal'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['compatibilidad_id'], ['compatibilidades.id_compatibilidad'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id', 'compatibilidad_id', name='uq_animal_compatibilidad')
    )
    op.create_table('animales_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id_animal'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id_estado'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id', 'estado_id', name='uq_animal_estado')
    )
    op.create_table('animales_personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id_animal'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id_persona'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id', 'persona_id', name='uq_animal_persona')
    )
    op.create_table('personas_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id_persona'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id_rol'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'rol_id', name='uq_persona_rol')
    )
    op.create_table('tareas_personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id_persona'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id_tarea'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tarea_id', 'persona_id', name='uq_tarea_persona')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id_persona'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('firebase_uid'),
    sa.UniqueConstraint('persona_id')
    )
    op.create_table('vacunas',
    sa.Column('id_vacuna', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=True),
    sa.Column('requiere_prox_dosis', sa.Boolean(), nullable=False),
    sa.Column('fecha_prox_dosis', sa.Date(), nullable=True),
    sa.Column('costo_aplicacion', sa.Numeric(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id_animal'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_vacuna')
    )
    op.create_table('visitas_veterinarias',
    sa.Column('id_visita', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('procedimiento', sa.Text(), nullable=False),
    sa.Column('info_adicional', sa.Text(), nullable=True),
    sa.Column('costo', sa.Numeric(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('veterinario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id_animal'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['veterinario_id'], ['personas.id_persona'], ),
    sa.PrimaryKeyConstraint('id_visita')
    )
    op.create_table('tratamientos',
    sa.Column('id_tratamiento', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas_veterinarias.id_visita'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_tratamiento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tratamientos')
    op.drop_table('visitas_veterinarias')
    op.drop_table('vacunas')
    op.drop_table('usuarios')
    op.drop_table('tareas_personas')
    op.drop_table('personas_roles')
    op.drop_table('animales_personas')
    op.drop_table('animales_estados')
    op.drop_table('animales_compatibilidades')
    op.drop_table('tareas')
    op.drop_table('roles')
    op.drop_table('personas')
    op.drop_table('estados')
    op.drop_table('compatibilidades')
    op.drop_table('animales')
    # ### end Alembic commands ###
