"""Agregar frecuencia_horas y hora_administracion a Tratamiento

Revision ID: 181c3192b188
Revises: b56b7a94c21e
Create Date: 2026-06-30 22:36:47.520128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181c3192b188'
down_revision = 'b56b7a94c21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tratamiento_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tratamientos', ['tratamiento_id'], ['id_tratamiento'], ondelete='SET NULL')

    with op.batch_alter_table('tratamientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frecuencia_horas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hora_administracion', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tratamientos', schema=None) as batch_op:
        batch_op.drop_column('hora_administracion')
        batch_op.drop_column('frecuencia_horas')

    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tratamiento_id')
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
