"""visita_id en tarea

Revision ID: 49d5a7341fa6
Revises: 53a1f83fd48b
Create Date: 2026-06-20 19:02:11.129523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d5a7341fa6'
down_revision = '53a1f83fd48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visita_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'visitas_veterinarias', ['visita_id'], ['id_visita'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visita_id')

    # ### end Alembic commands ###
