"""cambio asociaciones.py AnimalPersona rol_id

Revision ID: 53a1f83fd48b
Revises: c36cf862e44f
Create Date: 2026-05-30 19:35:19.402035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a1f83fd48b'
down_revision = 'c36cf862e44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animales_personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_animal_persona'), type_='unique')
        batch_op.create_unique_constraint('uq_animal_persona_rol', ['animal_id', 'persona_id', 'rol_id'])
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id_rol'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animales_personas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_animal_persona_rol', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_animal_persona'), ['animal_id', 'persona_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('rol_id')

    # ### end Alembic commands ###
