"""Cambiar ondelete a CASCADE para tratamiento_id en Tarea

Revision ID: 6bc31b547985
Revises: 181c3192b188
Create Date: 2026-07-01 00:00:35.607182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc31b547985'
down_revision = '181c3192b188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tareas_tratamiento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tratamientos', ['tratamiento_id'], ['id_tratamiento'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tareas_tratamiento_id_fkey'), 'tratamientos', ['tratamiento_id'], ['id_tratamiento'], ondelete='SET NULL')

    # ### end Alembic commands ###
