"""modelo historial_estado

Revision ID: 83b0d20d0125
Revises: 6bc31b547985
Create Date: 2026-07-10 17:15:58.214558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b0d20d0125'
down_revision = '6bc31b547985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animales_estados_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id_animal'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id_estado'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id_persona'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animales_estados_historial')
    # ### end Alembic commands ###
