"""initial

Revision ID: 98da967637fe
Revises: 
Create Date: 2026-05-29 14:39:38.360078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98da967637fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('activo')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
