"""hora en visitas_veterinarias

Revision ID: c29902270089
Revises: 49d5a7341fa6
Create Date: 2026-06-20 19:26:30.740696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29902270089'
down_revision = '49d5a7341fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas_veterinarias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas_veterinarias', schema=None) as batch_op:
        batch_op.drop_column('hora')

    # ### end Alembic commands ###
